### ISSUE TITLE
Change preview images to work as a link

### ISSUE THREAD

**Issue by d2s** [stefanjudis/tiny-helpers#15]
_Improvement idea:_
Improve usability by changing preview image to work as a link. Makes it faster to access tools as the small link on the bottom of the each tool is relatively small compared to the main preview image.

_Go to tool_ -type of links are useful, but it could be better to combine them to the header images for each of the tools. It would reduce height of each card, increasing amount of content people can see at once. Hover/Active -state for images could still include the _Go to_ -text as an CSS layer on top of an image.

**Comment by stefanjudis** [comment]
> Improve usability by changing preview image to work as a link

I think that's a good idea! 👍

> Hover/Active -state for images could still include the Go to -text as an CSS layer on top of an image.

Hmm... I'm not the biggest fan of hover animations because they make it harder for touch devices and such.

That said, I totally agree with making the screenshots links. :)

**Comment by stefanjudis** [comment]
The area of the preview images is now clickable and links to the helper URL. :) Thanks for the suggesetion. :)
