### ISSUE TITLE
Offer alternative to similar tools

### ISSUE THREAD

**Issue by dy** [stefanjudis/tiny-helpers#294]
Many tools have alternatives or closely related projects.

Eg. for viewing npm files there are at least 3 alternatives:
- [npmview](https://npmview.now.sh/package-name)
- [npmfs/package-name](https://npmfs.com/package/package-name/)
- [unpkg.com/package-name/](https://unpkg.com/browse/package-name@0.1.0/)
- [runpkg.com/?package-name](https://www.runpkg.com/?package-name@0.1.0/index.js)

Would be helpful to have them consolidated or mentioned, wouldn't it?

**Comment by stefanjudis** [comment]
I like that idea. What would you have in mind? How would you approach that?

**Comment by dy** [comment]
Just to start thinking - there's example from bundlephobia ticket https://github.com/pastelsky/bundlephobia/issues/179
![image](https://user-images.githubusercontent.com/300067/87483564-ff607580-c601-11ea-91b8-41174d9c8301.png).
Maybe a small icon with popup with a list of alternatives would work for the beginning?

**Comment by stefanjudis** [comment]
Thanks for giving more input! I think that's a great idea and from UI perspective I'm sure we could figure something out. What's not really clear to me is how we would model that from a data perspective. 

Currently, adding a new helper is fairly straightforward. How would we build the connections between the helpers? I don't think that we could expect a person adding a helper going over all the tools and figuring out what belongs together. The tagging approach is the closest I came to a maintainable solution. Looking for ideas there, too. 🙈

**Comment by dy** [comment]
Alternative tags is actually good idea. Eg. tag ‘alt:npmview’ would allow
grouping all npm viewers.

**Comment by stefanjudis** [comment]
Thanks @dy. I'm not sure if i like the idea of introducing a 2nd level.

But I'm not sure how another tag would help with the problem of maintenance and keeping/building all these connections? It would still mean that someone has to go through all the helpers to figure out if there is a similar one already or?

**Comment by dy** [comment]
Well, the baseline is - there is a _set_ of alternatives, so that set needs to be managed anyways.
The relation of _item_ - _set_ is many to many, therefore there needs to be an intermediate table/dict, and _tags_ is one of possible forms of it, already existing.
That's all theory of course.

**Comment by stefanjudis** [comment]
> Well, the baseline is - there is a set of alternatives, so that set needs to be managed anyways.

I understand and I believe that could have a lot of value.

> that set needs to be managed anyways

And that's where I don't see a way to make that possible without a massive time investment. Unfortunately, I can't commit to doing that and we can't expect people to scan 250+ tools when adding a new helper. :)

That's why I'd consider this idea out of scope. :/

**Comment by dy** [comment]
I don't see why there should be a massive initial time investment, that can be completely gradual, I see no value in that spend. I think the value is mostly in keeping track of alternatives if they become known, rather than running full-blown service. Maybe even having a per-tool short list of alternatives would be enough and possibly allow to reduce duplicates.
I used to keep track [packages alternatives](https://github.com/dy/analogs).
Regardless, feel free to close then.

**Comment by stefanjudis** [comment]
Alright. Thanks again for the suggestion, I'm closing this because of the mentioned reasons. :)
