### ISSUE TITLE
SVG Cloud generator

### ISSUE THREAD

**Issue by dy** [stefanjudis/tiny-helpers#307]
https://www.nephele.cloud/

**Comment by stefanjudis** [comment]
Thanks @dy. That's cool!  I'm not sure how it it helpw webdevs though. 🙈

> A collection of free single-purpose online tools for web developers...

**Comment by dy** [comment]
that’s from css-tricks, there’s a bunch of svg arrow/dividers/gradient
generators, clouds is just another type of background enhancer
