### ISSUE TITLE
Error in GitHub contributer icons

### ISSUE THREAD

**Issue by Ben1980** [stefanjudis/tiny-helpers#322]
One of the GitHub contributers has a icon error
![grafik](https://user-images.githubusercontent.com/919260/96964042-07d22180-150a-11eb-8af0-067110e047af.png)
I have this issue reproducable with Firefox developer 83.0b2

**Comment by stefanjudis** [comment]
Thanks Ben. :) Yeah I've see it but haven't had the time yet. 🙈

**Comment by stefanjudis** [comment]
Fixed. :)
