### ISSUE TITLE
Favor/bookmark tools

### ISSUE THREAD

**Issue by masc-98** [stefanjudis/tiny-helpers#338]
I would like to see that you can bookmark (locally) your favourite tools. In this way you can find them even faster next time on tiny-helpers. Yeaaah you could bookmark them in your browser too, but it would be a nice feature.

**Comment by stefanjudis** [comment]
Hello @masc-98, I'm not sure I understand what you're asking for.

You can always bookmark any URL on your machine. :) 

I'm closing here for now. Feel free to give more explanation. :)

**Comment by masc-98** [comment]
Sry, my english isn't that good.. ^^
Yeah i know. I mean that you have a section on the website, where you can see your booksmarks. It is clear that you can bookmark web pages in the browser, but bookmarking directly on tiny-helpers would be a "nice-to-have". You could store all bookmarks for example in cookies

**Comment by stefanjudis** [comment]
@masc-98 Yeah, I think I understand what you mean.

It's covered in this issue. https://github.com/stefanjudis/tiny-helpers/issues/118 And maybe one day I'll make it to implement it. :)
