### ISSUE TITLE
npm install (need version 12.*)

### ISSUE THREAD

**Issue by miko-github** [stefanjudis/tiny-helpers#346]
Hi there :wave: 

- first i fork
- then run below to clone from my github
    `$ git clone https://github.com/miko-github/tiny-helpers.git`
- next, i use `$ cd on tiny-helpers` to change current directory
- and run
    `$ npm install`
- but this not work and show me error (i think, that need nodejs with version 12? :thinking: )
#### Error message
<pre><span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> EBADENGINE
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">engine</font> Unsupported engine
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">engine</font> Not compatible with your version of node/npm: tiny-helpers@1.0.0
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">notsup</font> Not compatible with your version of node/npm: tiny-helpers@1.0.0
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">notsup</font> Required: {&quot;node&quot;:&quot;^12.14.0&quot;}
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">notsup</font> Actual:   {&quot;npm&quot;:&quot;7.9.0&quot;,&quot;node&quot;:&quot;v14.16.0&quot;}

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /home/admin/.npm/_logs/2021-04-22T18_18_39_733Z-debug.log</pre>

- i searching in google but not found anything, actually, are you can update node version for newer things! :hugs:

**Comment by miko-github** [comment]
thank you :heart:

**Comment by colinswinney** [comment]
I've just received a similar message following the same steps Miko listed above.

```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: tiny-helpers@1.0.0
npm ERR! notsup Not compatible with your version of node/npm: tiny-helpers@1.0.0
npm ERR! notsup Required: {"node":"^14.16.0"}
npm ERR! notsup Actual:   {"npm":"7.24.0","node":"v16.10.0"}
```

**Comment by stefanjudis** [comment]
Shoot... It's update time again. You're on node 16. Will update if I find a moment or could you update the nvmrc?

**Comment by colinswinney** [comment]
I just submitted a pull request changing the nvmrc to 16.10.  Thanks!

**Comment by smrlo** [comment]
Just went through the contibuting sequence and got a similar error:

> npm ERR! code EBADENGINE
> npm ERR! engine Unsupported engine
> npm ERR! engine Not compatible with your version of node/npm: tiny-helpers@1.0.0
> npm ERR! notsup Not compatible with your version of node/npm: tiny-helpers@1.0.0
> npm ERR! notsup Required: {"node":"^16"}
> npm ERR! notsup Actual:   {"npm":"8.5.5","node":"v17.2.0"}

**Comment by stefanjudis** [comment]
I'll update the `nvmrc` once Node 16 goes out of life. :) 

If you use a Node version manager, please use Node 16 or add a `JSON` file manually to [the `helpers` directory](https://github.com/stefanjudis/tiny-helpers/tree/primary/helpers).
