### ISSUE TITLE
not able to clone

### ISSUE THREAD

**Issue by WitchDevelops** [stefanjudis/tiny-helpers#504]
Maybe I'm doing it wrong, but with GitHub desktop I'm getting this error:
![image](https://github.com/stefanjudis/tiny-helpers/assets/112077394/7658c724-5b61-4b71-b9c2-7dae5e3292f6)

While when trying to contribute on Codespaces I'm seeing this after running `npm ci`:
![image](https://github.com/stefanjudis/tiny-helpers/assets/112077394/f4d61f7e-4036-4b8f-9f47-33dcde29c3ca)

**Comment by stefanjudis** [comment]
Oh wow. You're running into two different issues here.

1) Looks like one file has an invalid character that doesn't work well. Let me rename it.
2) The project right now required Node 18 and should be bumped to Node 20.

I'll do both things right now. :)

**Comment by WitchDevelops** [comment]
That solved it, thanks!

**Comment by stefanjudis** [comment]
Yay! 🎉
