### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by kamalkech** [stefanjudis/tiny-helpers#510]
Expect search and get answer: ENOENT: no such file or directory, open '/var/folders/z9/7lnm0tg91rqbrvf0wvs18gh80000gn/T/chromium-pack/fonts.tar.br'

**Comment by stefanjudis** [comment]
Hey @kamalkech, 

I assume you have problems with running tiny-helpers. Please provide information on your taken actions or a reproducible example and explain the problem. Unfortunately, your message isn't actionable so I'm closing this issue.

If you provide more information, I'm happy to reopen it.
