### ISSUE TITLE
Does https://www.stefanjudis.com/blog/how-to-use-headless-chrome-in-serverless-functions/ still work for you?

### ISSUE THREAD

**Issue by ryancwalsh** [stefanjudis/tiny-helpers#516]
Thanks for that article!

I'm in a similar situation.

I'd love to use the free Vercel Hobby plan. I could use my $6/mo Digital Ocean server, but I'd need to upgrade its Ubuntu, which would be a pain.

To get your https://www.stefanjudis.com/blog/how-to-use-headless-chrome-in-serverless-functions/ solution working I needed this advice: https://github.com/puppeteer/puppeteer/issues/11052#issuecomment-1738988091

Now it builds fine.

But when I try on Vercel, I still get the timeout.

Does it still work for you these days?

Thanks!

**Comment by 0x-m1cro** [comment]
I wish to know likewise, bump. Currently im using render, but the 12 minute timeout is pain. So before i change to vercel i need to confirm. Thank you!

**Comment by ryancwalsh** [comment]
Cool, it's helpful to hear that it's still working for you. Thanks.
