### ISSUE TITLE
No images, api/screenshot down?

### ISSUE THREAD

**Issue by dzschille** [stefanjudis/tiny-helpers#524]
There seems to be an error with https://tiny-helpers.dev/api/screenshot/ :
![grafik](https://github.com/stefanjudis/tiny-helpers/assets/572402/7c4a5dd7-d510-4691-b395-41e754eb7c4a)

**Comment by stefanjudis** [comment]
Yeah, the headless chrome route broke on vercel. :/ eventually I'll look into it. :)

**Comment by Cardoso222** [comment]
Same issue here

**Comment by stefanjudis** [comment]
Should be back. :)
