### ISSUE TITLE
Not accepting new helpers?

### ISSUE THREAD

**Issue by jikkuatwork** [stefanjudis/tiny-helpers#537]
Hi I just posted a helper and just realised there a few other helpers that were not merged. Is the project not accepting new PRs?

**Comment by stefanjudis** [comment]
There also PRs that has been merged 👉 https://github.com/stefanjudis/tiny-helpers/pulls?q=is%3Apr+is%3Aclosed

Life's just busy you know. :)

**Comment by jikkuatwork** [comment]
Shall I suggest that we can add an option for the builders to add the
screenshots?

--
Jikku Jose
Co-founder, StoryBrain <https://storybrain.com>

**Comment by jikkuatwork** [comment]
I think they reduced the memory/execution limits in hobby plan causing this.

**Comment by stefanjudis** [comment]
Yeah might be — I'm not on the hobby plan though. At some point I'll set up a real server for it. 🤷

For not it's just broken. :/
