### ISSUE TITLE
Open Source only?

### ISSUE THREAD

**Issue by loilo** [stefanjudis/tiny-helpers#75]
I'm about to add a helper which I find vastly useful ([crontab.guru](https://crontab.guru)) but which is not open source (and for which I cannot add a maintainer's GitHub handle). Even worse, there's no single known maintainer but only the company that created the tool (which is discouraged in the CLI).

So, to get some clarification on this: Are non-OSS tools welcome on the page? If not, that should probably go into the Contributing section.

**Comment by stefanjudis** [comment]
Thanks for the feedback Florian. :) @loilo 

> Are non-OSS tools welcome on the page?

Yes. And the page includes lots of them already. :) 

> Even worse, there's no single known maintainer but only the company that created the tool

You'll find information about that in the new docs. 👇

https://github.com/stefanjudis/tiny-helpers/blob/master/CONTRIBUTING.md
