### ISSUE TITLE
New Helper– UTM Tag Generator

### ISSUE THREAD

**Issue by chrisblakley** [stefanjudis/tiny-helpers#90]
I found this list last week and thought it'd be a good place to share my UTM Tag generator. I re-wrote it this weekend to simplify it and make other improvements so now I'm ready to share it. I apologize that I do not use npm, so I can't submit a pull request per the instructions.

Here's the URL: https://gearside.com/utm/

Here's what I'd think the appropriate JSON would be:
```json
{
	"name": "Easy UTM Tag Generator",
	"desc": "Creating UTM tags doesn't have to be so complicated! This simple tool will help guide you through generating a superior URL for your campaigns.",
	"url": "https://gearside.com/utm/",
	"tags": [
		"HTTP",
		"Misc"
	],
	"maintainers": [
		"chrisblakley"
	],
	"addedAt": "2020-01-18"
}
```

**Comment by badcat** [comment]
I had a few helpers to add as well, but no need to use NPM so this was a no go for me - I suppose I'm just not a real developer but still like these focused tools.  :)

**Comment by fhemberger** [comment]
@chrisblakley Added your UTM helper, thanks!
