### ISSUE TITLE
bug: exo font not loaded

### ISSUE THREAD

**Issue by donroyco** [stefanjudis/tiny-helpers#93]
When opening the website the console spits out a 404 error that the Exo font can not be loaded.

<img width="849" alt="Console errors showing 404s" src="https://user-images.githubusercontent.com/1763537/72677952-d1aad180-3aa1-11ea-89ff-24b2223d07d1.png">

Along, the favicons (32x32 and 16x16) can't be found.

Details browser: Chrome latest version.

**Comment by stefanjudis** [comment]
Aaah... recent refactoring... 🤦‍♂️ Will be fixed soon. Thank you for reporting. :(

**Comment by stefanjudis** [comment]
Fixed. :)

**Comment by donroyco** [comment]
You're welcome!
