### ISSUE TITLE
a11y: logo not clickable to go to main page

### ISSUE THREAD

**Issue by donroyco** [stefanjudis/tiny-helpers#94]
To improve accessibility and adhere conventions, I would recommend to make the logo clickable so you can easily return to the main page. See more details [here](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page).

**Comment by stefanjudis** [comment]
Agree and we'll handle it soon. :) (it was already hidden and mentioned in another issue). :) 

(https://github.com/stefanjudis/tiny-helpers/issues/5)
